### ISSUE TITLE
"Updating existing project", but project does not exist

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-py#16]
Using the ontology in https://github.com/dhlab-basel/knora-large-texts. I have just initialised the repository using `knora-api/webapi/scripts/graphdb-se-local-init-knora-test.sh`, so the project I'm creating doesn't exist yet.

```
$ knora-create-ontology book-onto.json
/usr/local/lib/python3.7/site-packages/knora
Ontology is syntactically correct and passed validation!
Updating existing project!
['test', 'knora-py']
Traceback (most recent call last):
  File "/usr/local/bin/knora-create-ontology", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/knora/create_ontology.py", line 283, in main
    program(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/knora/create_ontology.py", line 72, in program
    keywords=ontology["project"].get("keywords")
  File "/usr/local/lib/python3.7/site-packages/knora/knora.py", line 296, in update_project
    self.on_api_error(req)
  File "/usr/local/lib/python3.7/site-packages/knora/knora.py", line 163, in on_api_error
    raise KnoraError("KNORA-ERROR: status code=" + str(res.status_code) + "\nMessage:" + res.text)
knora.knora.KnoraError: KNORA-ERROR: status code=404
Message:{"error":"org.knora.webapi.NotFoundException: Project 'http://rdfh.ch/projects/00FD' not found. Aborting update request."}
```

**Comment by subotic** [comment]
AFAIK `knora-create-ontology` should create the project, if it is not there.

**Comment by benjamingeer** [comment]
> AFAIK `knora-create-ontology` should create the project, if it is not there.

It looked like it did create the project the first time I ran it. But after I dropped the repository and rebuilt it from scratch (using `knora-api/webapi/scripts`), I got this error.

**Comment by benjamingeer** [comment]
@subotic I dropped and reloaded the repository in GraphDB, and ran this little test program:

```python
#!/usr/bin/env python3

from knora import Knora

con = Knora("http://0.0.0.0:3333")
con.login("root@example.com", "test")
project = con.get_project("00FD")
print(project)
```

And it printed the project info, which isn't in the repository:

```python
{'description': [{'value': 'A ontology for testing Knora with large books', 'language': 'en'}], 'id': 'http://rdfh.ch/projects/00FD', 'keywords': ['knora-py', 'test'], 'logo': None, 'longname': 'large books', 'ontologies': [], 'selfjoin': False, 'shortcode': '00FD', 'shortname': 'books', 'status': True}
```

Could it be that redis is persistently caching the project, even though the project is no longer in the triplestore? I restarted redis but that doesn't help.

**Comment by benjamingeer** [comment]
Aha, when redis starts it says:

```
2270:M 10 Oct 2019 09:15:55.889 * DB loaded from disk: 0.001 seconds
```

And when it stops it says:

```
2270:M 10 Oct 2019 09:29:31.247 * DB saved on disk
```

Now I see that it saves a file called `dump.rdb`. Moving this bug to `knora-api`.
